using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using ModelContextProtocol.Server;
using KspControl.Host;
var builder = Microsoft.Extensions.Hosting.Host.CreateApplicationBuilder(args);
builder.Logging.AddConsole(options => options.LogToStandardErrorThreshold = LogLevel.Trace);
builder.Services.AddSingleton<BridgeClient>();
builder.Services.AddMcpServer().WithStdioServerTransport().WithTools<ObservationTools>();
await builder.Build().RunAsync();
